"""Real Material Design Icons (MDI) catalog lookup.

Backs both directions of LXMF's ``FIELD_ICON_APPEARANCE`` (0x04):
rendering a real icon shape for an inbound contact's icon name (see
``messaging.py``'s ``_render_appearance_svg``, which used to draw only
the icon name's first letter as a text placeholder), and this operator's
own icon picker in the browser, which fetches ``static/data/mdi_icons.json``
directly rather than going through this module — this module is the
server-side rendering path only.

Data: ``static/data/mdi_icons.json`` (name -> SVG path ``"d"`` data,
~7400 entries) and ``static/data/mdi_categories.json`` (category ->
[names], ~61 categories) — both generated from the real ``@mdi/js`` npm
package (Apache-2.0 — see ``NOTICE.md``) and shared verbatim with the
NomadPortal-Android sister project, which sources from the exact same
upstream (Templarian/MaterialDesign). Loaded once, lazily, on first
lookup rather than at import time, so a missing/corrupt asset degrades
every lookup to "not found" (callers fall back to a letter glyph) instead
of breaking app startup.
"""

import json
import logging
import os
import re
import threading

log = logging.getLogger(__name__)

# Legitimate SVG path "d" data is only command letters, digits, '.', '-',
# ',', and whitespace — never '<', '>', or '"'. get_path()'s result lands
# directly in a hand-built SVG string (messaging.py's
# _render_appearance_svg) that's stored and served to every viewer of a
# contact's icon, not just re-parsed JSON — an allowlist here is cheap
# insurance against a corrupted/tampered data file, on the same principle
# app.js's own _safeSvgPath applies client-side to the same data.
_SVG_PATH_RE = re.compile(r'^[MmLlHhVvCcSsQqTtAaZz0-9.,\-\s]+$')

# nomadnet_web/ and static/ are sibling directories both under the repo
# root in dev and under /app in the Docker image (see Dockerfile's
# `COPY nomadnet_web/ ./nomadnet_web/` + `COPY static/ ./static/`) — this
# resolves correctly in both layouts without needing an app-context-bound
# Flask path helper, since icon rendering (messaging.py) runs from a
# background LXMF delivery thread with no request/app context available.
_STATIC_DATA_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "static", "data",
)
_ICONS_FILE = os.path.join(_STATIC_DATA_DIR, "mdi_icons.json")

_lock = threading.Lock()
_paths: dict | None = None  # name -> SVG path "d" data; {} if load failed


def _load() -> None:
    global _paths
    if _paths is not None:
        return
    with _lock:
        if _paths is not None:  # re-check: another thread may have loaded first
            return
        try:
            # utf-8-sig: the bundled file (generated by the sister
            # project's own asset pipeline) carries a UTF-8 BOM. Plain
            # "utf-8" chokes on it (json.load raises "Unexpected UTF-8
            # BOM"), which would have made every single lookup fail —
            # caught by this module's own test suite, not guessed.
            # utf-8-sig transparently strips a BOM when present and is a
            # no-op when it isn't, so it's the right choice regardless of
            # whether a future regeneration of this file keeps one.
            with open(_ICONS_FILE, "r", encoding="utf-8-sig") as fh:
                _paths = json.load(fh)
            log.info("Loaded %d Material Design Icons", len(_paths))
        except Exception as exc:
            log.warning(
                "Could not load MDI icon data from %s (%s) — icon rendering "
                "falls back to first-letter glyphs", _ICONS_FILE, exc,
            )
            _paths = {}


def _normalize(name: str) -> str:
    """Real MDI names are kebab-case (e.g. ``"account-supervisor"``).
    Accept space/underscore variants too — this app's own older 1-2 char
    glyph values still round-trip harmlessly (just never match), and some
    real-world senders use underscores instead of hyphens."""
    return (name or "").strip().lower().replace(" ", "-").replace("_", "-")


def get_path(name: str) -> str | None:
    """Return the SVG path ``d`` data for a real MDI icon name, or
    ``None`` if unrecognized (including while the catalog is mid-load —
    callers must treat that identically to "not found", never block on
    it: this module makes no availability guarantee about *when* it
    finishes loading, only that a lookup is always safe to call) or a
    matching entry's value fails the allowlist check above."""
    _load()
    path = _paths.get(_normalize(name))
    if path is not None and not _SVG_PATH_RE.match(path):
        log.warning("MDI entry for %r failed the SVG-path allowlist — treating as not found", name)
        return None
    return path


def is_loaded() -> bool:
    """True once a load attempt has completed (whether or not the asset
    read actually succeeded) — mirrors the Android sister project's own
    ``MdiIconRepository.isLoaded()`` contract."""
    return _paths is not None
